/*Generated by `npx supabase db dump --role-only` with some modifications*/
SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

ALTER ROLE "anon" SET "statement_timeout" TO '3s';

ALTER ROLE "authenticated" SET "statement_timeout" TO '8s';

ALTER ROLE "authenticator" SET "statement_timeout" TO '8s';

DO $$ BEGIN
    CREATE ROLE "snaplet_readonly";
EXCEPTION WHEN duplicate_object THEN null;
END;$$;

GRANT "pg_read_all_data" TO "snaplet_readonly" GRANTED BY "postgres";

RESET ALL;
