// This transform config was generated by Snaplet.
// Snaplet found fields that may contain personally identifiable information (PII)
// and used that to populate this file.
import { copycat } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
function randomString(length: number) {
    const characters =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+=-*/";
    let result = "";
    for (let i = 0; i < length; ++i) {
        result += characters.charAt(Math.floor(Math.random() * characters.length));
    }
    return result;
}
//change hash key to constant value to prevent values from changing between snapshots
copycat.setHashKey(copycat.generateHashKey(randomString(16)));
export default defineConfig({
    select: {
        auth: {
            // Exclude the data for all the tables in auth schema
            $default: "structure",
            // Except for the these tables
            identities: true,
            users: true,
        },
        storage: {
            migrations: "structure",
            objects: "structure"
        },
        pgsodium: {
            key: "structure",
        },
        vault: {
            secrets: "structure",
        },
    },
    transform: {
        auth: {
            identities({ row }) {
                row.identity_data!['email'] = copycat.email(row.identity_data!['email']);
                return {
                    identity_data: row.identity_data
                }
            },
            users({ row }) {
                return {
                    email: copycat.email(row.email, {
                        limit: 255,
                    }),
                    // unencrypted: password
                    encrypted_password:
                        "$2a$08$YjXT4bhQpp3xqyCf3eMbEefqsM1.JJopAanogm3bYs6sAahtRVrjK",
                    phone: copycat.phoneNumber(row.phone),
                };
            },
        },
    },
    subset: {
        enabled: false,
        version: "3",
        targets: [
            {
                table: "any",
                percent: 100,
            },
        ],
    },
});
